version: '3.7'
services:
  blocky:
    image: adi3000/blocky:fb-dns-cache-switch
    ports:
      - '54:53/tcp'
      - '54:53/udp'
      - '4000:4000/tcp'
    environment:
      - TZ=Europe/Berlin # Optional to synchronize the log timestamp with host
    volumes:
      # config file
      - ./blocky/config.yml:/app/config.yml

  blocky-frontend:
    depends_on:
      - blocky
    image: ghcr.io/mozart409/blocky-frontend:latest
    ports:
      - '81:80'